name: Execute lint/tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - 'requirements-dev.txt'
      - '.gitignore'
      - './terraform'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./primer-api
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make init

      - name: Run pre-commit hooks
        shell: bash
        run: pre-commit run --all-files
      
      - name: Execute bandit
        run: make bandit

  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./primer-api
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make init

      - name: Unit tests
        run: make unit
        timeout-minutes: 1

  deploy:
    runs-on: ubuntu-20.04
    if: github.base_ref == ''  # skip if PR
    needs: [validate, tests]
    defaults:
      run:
        working-directory: ./primer-api

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP file
        run: zip -q -r ../primer-api.zip app requirements.txt

      - name: Upload ZIP to S3
        uses: zdurham/s3-upload-github-action@master
        env:
          FILE: ./primer-api.zip
          AWS_REGION: 'eu-west-1'
          S3_BUCKET: ${{ secrets.BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
